In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
orders_products_merged = pd.read_pickle(r'C:\Users\hp\Desktop\Task 4\Task 4.2\Instacart Basket Analysis\02 Data\Prepared Data\orders_products_merged_deriving.pkl')

In [28]:
path= r'C:\Users\hp\Desktop\Task 4\Task 4.2\Instacart Basket Analysis'

In [3]:
df = orders_products_merged[:1000000]

In [4]:
df.head(10)

,order_id,user_id,eval_set,order_number,order_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,_merge,product_name,aisle_id,department_id,prices,exists,price_range,Busiest_day,Busiest_days,busiest_period_of_day
0,2539329,1,prior,1,2,8,1.0,196,1,0,both,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Average orders
1,2398795,1,prior,2,3,7,15.0,196,1,1,both,Soda,77,7,9.0,both,Mid-range product,Regularly busy,slowest busy,Average orders
2,473747,1,prior,3,3,12,21.0,196,1,1,both,Soda,77,7,9.0,both,Mid-range product,Regularly busy,slowest busy,Most orders
3,2254736,1,prior,4,4,7,29.0,196,1,1,both,Soda,77,7,9.0,both,Mid-range product,Least busy,slowest busy,Average orders
4,431534,1,prior,5,4,15,28.0,196,1,1,both,Soda,77,7,9.0,both,Mid-range product,Least busy,slowest busy,Most orders
5,3367565,1,prior,6,2,7,19.0,196,1,1,both,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Average orders
6,550135,1,prior,7,1,9,20.0,196,1,1,both,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest day,Most orders
7,3108588,1,prior,8,1,14,14.0,196,2,1,both,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest day,Most orders
8,2295261,1,prior,9,1,16,0.0,196,4,1,both,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest day,Most orders
9,2550362,1,prior,10,4,8,30.0,196,1,1,both,Soda,77,7,9.0,both,Mid-range product,Least busy,slowest busy,Average orders

In [5]:
orders_products_merged.groupby('product_name')

__Q.2 In this Exercise, you learned how to find the aggregated mean of the “order_number” column grouped by “department_id” for a subset of your dataframe. Now, repeat this process for the entire dataframe__

In [6]:
df.groupby('department_id').agg({'order_number': ['mean']})

              order_number
                      mean
department_id
4                18.825780
7                17.472355
13               17.993423
14               19.246334
16               19.463012
17               11.294069
19               19.305237
20               17.599636

In [7]:
df.groupby('department_id')['order_number'].mean()

department_id
4     18.825780
7     17.472355
13    17.993423
14    19.246334
16    19.463012
17    11.294069
19    19.305237
20    17.599636
Name: order_number, dtype: float64

In [8]:
df.groupby('department_id').agg({'order_number': ['mean', 'min', 'max']})

              order_number
                      mean min max
department_id
4                18.825780   1  99
7                17.472355   1  99
13               17.993423   1  99
14               19.246334   1  99
16               19.463012   1  99
17               11.294069   1  98
19               19.305237   1  99
20               17.599636   1  99

In [9]:
orders_products_merged.describe()

,order_id,user_id,order_number,order_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,aisle_id,department_id,prices
count,3.240486e+07,3.240486e+07,3.240486e+07,3.240486e+07,3.240486e+07,3.240486e+07,3.240486e+07,3.240486e+07,3.240486e+07,3.240486e+07,3.240486e+07,3.240486e+07
mean,1.710745e+06,1.029372e+05,1.714230e+01,2.738867e+00,1.342515e+01,1.045674e+01,2.559866e+04,8.352547e+00,5.895873e-01,7.119612e+01,9.919792e+00,1.198023e+01
std,9.872988e+05,5.946610e+04,1.753532e+01,2.090077e+00,4.246380e+00,8.846237e+00,1.408400e+04,7.127071e+00,4.919087e-01,3.821139e+01,6.281485e+00,4.956554e+02
min,2.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00
25%,8.559470e+05,5.142200e+04,5.000000e+00,1.000000e+00,1.000000e+01,4.000000e+00,1.354400e+04,3.000000e+00,0.000000e+00,3.100000e+01,4.000000e+00,4.200000e+00
50%,1.711049e+06,1.026160e+05,1.100000e+01,3.000000e+00,1.300000e+01,7.000000e+00,2.530200e+04,6.000000e+00,1.000000e+00,8.300000e+01,9.000000e+00,7.400000e+00
75%,2.565499e+06,1.543890e+05,2.400000e+01,5.000000e+00,1.600000e+01,1.400000e+01,3.794700e+04,1.100000e+01,1.000000e+00,1.070000e+02,1.600000e+01,1.130000e+01
max,3.421083e+06,2.062090e+05,9.900000e+01,6.000000e+00,2.300000e+01,3.000000e+01,4.968800e+04,1.450000e+02,1.000000e+00,1.340000e+02,2.100000e+01,9.999900e+04

__Q.3 Analyze the result. How do the results for the entire dataframe differ from those of the subset? Include your comments in a markdown cell below the executed code__

_The mean in subset is number 17 which has higher mean in the full dataframe as it shown above._

__Q.4 Follow the instructions in the Exercise for creating a loyalty flag for existing customers using the transform() and loc() functions.__

In [10]:
orders_products_merged['max_order'] = orders_products_merged.groupby(['user_id'])['order_number'].transform(np.max)

In [11]:
orders_products_merged.head(15)

,order_id,user_id,eval_set,order_number,order_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,...,product_name,aisle_id,department_id,prices,exists,price_range,Busiest_day,Busiest_days,busiest_period_of_day,max_order
0,2539329,1,prior,1,2,8,1.0,196,1,0,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Average orders,10
1,2398795,1,prior,2,3,7,15.0,196,1,1,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,slowest busy,Average orders,10
2,473747,1,prior,3,3,12,21.0,196,1,1,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,slowest busy,Most orders,10
3,2254736,1,prior,4,4,7,29.0,196,1,1,...,Soda,77,7,9.0,both,Mid-range product,Least busy,slowest busy,Average orders,10
4,431534,1,prior,5,4,15,28.0,196,1,1,...,Soda,77,7,9.0,both,Mid-range product,Least busy,slowest busy,Most orders,10
5,3367565,1,prior,6,2,7,19.0,196,1,1,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Average orders,10
6,550135,1,prior,7,1,9,20.0,196,1,1,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest day,Most orders,10
7,3108588,1,prior,8,1,14,14.0,196,2,1,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest day,Most orders,10
8,2295261,1,prior,9,1,16,0.0,196,4,1,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest day,Most orders,10
9,2550362,1,prior,10,4,8,30.0,196,1,1,...,Soda,77,7,9.0,both,Mid-range product,Least busy,slowest busy,Average orders,10
10,2968173,15,prior,15,1,9,7.0,196,2,0,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest day,Most orders,22
11,1870022,15,prior,17,2,16,8.0,196,6,1,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,22
12,1911383,15,prior,18,2,11,7.0,196,1,1,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,22
13,2715276,15,prior,21,1,9,7.0,196,1,1,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest day,Most orders,22
14,487368,15,prior,22,1,10,14.0,196,1,1,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest day,Most orders,22

In [12]:
orders_products_merged.head(100)

,order_id,user_id,eval_set,order_number,order_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,...,product_name,aisle_id,department_id,prices,exists,price_range,Busiest_day,Busiest_days,busiest_period_of_day,max_order
0,2539329,1,prior,1,2,8,1.0,196,1,0,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Average orders,10
1,2398795,1,prior,2,3,7,15.0,196,1,1,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,slowest busy,Average orders,10
2,473747,1,prior,3,3,12,21.0,196,1,1,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,slowest busy,Most orders,10
3,2254736,1,prior,4,4,7,29.0,196,1,1,...,Soda,77,7,9.0,both,Mid-range product,Least busy,slowest busy,Average orders,10
4,431534,1,prior,5,4,15,28.0,196,1,1,...,Soda,77,7,9.0,both,Mid-range product,Least busy,slowest busy,Most orders,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,3226575,360,prior,1,5,12,1.0,196,1,0,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,3
96,1469869,377,prior,3,5,17,3.0,196,9,0,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Average orders,3
97,1927023,387,prior,2,4,10,22.0,196,3,0,...,Soda,77,7,9.0,both,Mid-range product,Least busy,slowest busy,Most orders,8
98,858092,420,prior,4,1,19,30.0,196,2,0,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest day,Average orders,22
99,119314,420,prior,5,3,19,16.0,196,2,1,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,slowest busy,Average orders,22

In [13]:
orders_products_merged.head(100)

,order_id,user_id,eval_set,order_number,order_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,...,product_name,aisle_id,department_id,prices,exists,price_range,Busiest_day,Busiest_days,busiest_period_of_day,max_order
0,2539329,1,prior,1,2,8,1.0,196,1,0,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Average orders,10
1,2398795,1,prior,2,3,7,15.0,196,1,1,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,slowest busy,Average orders,10
2,473747,1,prior,3,3,12,21.0,196,1,1,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,slowest busy,Most orders,10
3,2254736,1,prior,4,4,7,29.0,196,1,1,...,Soda,77,7,9.0,both,Mid-range product,Least busy,slowest busy,Average orders,10
4,431534,1,prior,5,4,15,28.0,196,1,1,...,Soda,77,7,9.0,both,Mid-range product,Least busy,slowest busy,Most orders,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,3226575,360,prior,1,5,12,1.0,196,1,0,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,3
96,1469869,377,prior,3,5,17,3.0,196,9,0,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Average orders,3
97,1927023,387,prior,2,4,10,22.0,196,3,0,...,Soda,77,7,9.0,both,Mid-range product,Least busy,slowest busy,Most orders,8
98,858092,420,prior,4,1,19,30.0,196,2,0,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest day,Average orders,22
99,119314,420,prior,5,3,19,16.0,196,2,1,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,slowest busy,Average orders,22

In [14]:
orders_products_merged.loc[orders_products_merged['max_order'] > 40, 'loyalty_flag'] = 'Loyal customer'
orders_products_merged.loc[(orders_products_merged['max_order'] <= 40) & (orders_products_merged['max_order'] > 10), 'loyalty_flag'] = 'Regular customer'
orders_products_merged.loc[orders_products_merged['max_order'] <= 10, 'loyalty_flag'] = 'New customer'

In [15]:
orders_products_merged[['user_id', 'loyalty_flag', 'order_number']].head(60)

    user_id      loyalty_flag  order_number
0         1      New customer             1
1         1      New customer             2
2         1      New customer             3
3         1      New customer             4
4         1      New customer             5
5         1      New customer             6
6         1      New customer             7
7         1      New customer             8
8         1      New customer             9
9         1      New customer            10
10       15  Regular customer            15
11       15  Regular customer            17
12       15  Regular customer            18
13       15  Regular customer            21
14       15  Regular customer            22
15       19      New customer             2
16       19      New customer             5
17       19      New customer             7
18       21  Regular customer            10
19       31  Regular customer            10
20       31  Regular customer            17
21       43  Regular customer             6
22       43  Regular customer             9
23       52  Regular customer             1
24       52  Regular customer             2
25       52  Regular customer             3
26       52  Regular customer             5
27       52  Regular customer             7
28       52  Regular customer             9
29       52  Regular customer            10
30       52  Regular customer            11
31       52  Regular customer            12
32       52  Regular customer            15
33       52  Regular customer            17
34       52  Regular customer            18
35       52  Regular customer            19
36       52  Regular customer            21
37       67  Regular customer             1
38       67  Regular customer             2
39       67  Regular customer             3
40       67  Regular customer             4
41       67  Regular customer             5
42       67  Regular customer             6
43       67  Regular customer             8
44       67  Regular customer             9
45       67  Regular customer            10
46       67  Regular customer            11
47       67  Regular customer            12
48       67  Regular customer            13
49       67  Regular customer            14
50       67  Regular customer            16
51       67  Regular customer            18
52       67  Regular customer            19
53       67  Regular customer            21
54       67  Regular customer            22
55       67  Regular customer            23
56       81      New customer             3
57       81      New customer             5
58       82  Regular customer             1
59       82  Regular customer             3

In [16]:
orders_products_merged.shape

(32404859, 22)

__Q.5 The marketing team at Instacart wants to know whether there’s a difference between the spending habits of the three types of customers you identified. Use the loyalty flag you created and check the basic statistics of the product prices for each loyalty category (Loyal Customer, Regular Customer, and New Customer). What you’re trying to determine is whether the prices of products purchased by loyal customers differ from those purchased by regular or new customers.__

In [17]:
orders_products_merged.groupby('loyalty_flag').agg({'prices': ['mean', 'min', 'max']})

                     prices
                       mean  min      max
loyalty_flag
Loyal customer    10.386336  1.0  99999.0
New customer      13.294670  1.0  99999.0
Regular customer  12.495717  1.0  99999.0

In [18]:
df.groupby('department_id')['order_number'].mean()

department_id
4     18.825780
7     17.472355
13    17.993423
14    19.246334
16    19.463012
17    11.294069
19    19.305237
20    17.599636
Name: order_number, dtype: float64

__Q.6 The team now wants to target different types of spenders in their marketing campaigns. This can be achieved by looking at the prices of the items people are buying. Create a spending flag for each user based on the average price across all their orders using the following criteria:__

__1)If the mean of the prices of products purchased by a user is lower than 10, then flag them as a “Low spender.”__

__2)If the mean of the prices of products purchased by a user is higher than or equal to 10, then flag them as a “High spender.”__

In [19]:
#Create avg price
orders_products_merged['avg_price']=orders_products_merged.groupby('user_id').agg({'prices': ['mean']})

In [20]:
orders_products_merged.loc[orders_products_merged['avg_price'] >= 10, 'spending_flag'] = 'High spender'

In [21]:
orders_products_merged.loc[orders_products_merged['avg_price'] < 10, 'spending_flag'] = 'Low spender'

In [22]:
orders_products_merged.head(50)

,order_id,user_id,eval_set,order_number,order_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,...,prices,exists,price_range,Busiest_day,Busiest_days,busiest_period_of_day,max_order,loyalty_flag,avg_price,spending_flag
0,2539329,1,prior,1,2,8,1.0,196,1,0,...,9.0,both,Mid-range product,Regularly busy,Regularly busy,Average orders,10,New customer,NaN,NaN
1,2398795,1,prior,2,3,7,15.0,196,1,1,...,9.0,both,Mid-range product,Regularly busy,slowest busy,Average orders,10,New customer,6.367797,Low spender
2,473747,1,prior,3,3,12,21.0,196,1,1,...,9.0,both,Mid-range product,Regularly busy,slowest busy,Most orders,10,New customer,7.515897,Low spender
3,2254736,1,prior,4,4,7,29.0,196,1,1,...,9.0,both,Mid-range product,Least busy,slowest busy,Average orders,10,New customer,8.197727,Low spender
4,431534,1,prior,5,4,15,28.0,196,1,1,...,9.0,both,Mid-range product,Least busy,slowest busy,Most orders,10,New customer,8.205556,Low spender
5,3367565,1,prior,6,2,7,19.0,196,1,1,...,9.0,both,Mid-range product,Regularly busy,Regularly busy,Average orders,10,New customer,9.189189,Low spender
6,550135,1,prior,7,1,9,20.0,196,1,1,...,9.0,both,Mid-range product,Regularly busy,Busiest day,Most orders,10,New customer,8.471429,Low spender
7,3108588,1,prior,8,1,14,14.0,196,2,1,...,9.0,both,Mid-range product,Regularly busy,Busiest day,Most orders,10,New customer,7.466990,Low spender
8,2295261,1,prior,9,1,16,0.0,196,4,1,...,9.0,both,Mid-range product,Regularly busy,Busiest day,Most orders,10,New customer,8.781633,Low spender
9,2550362,1,prior,10,4,8,30.0,196,1,1,...,9.0,both,Mid-range product,Least busy,slowest busy,Average orders,10,New customer,7.607895,Low spender
10,2968173,15,prior,15,1,9,7.0,196,2,0,...,9.0,both,Mid-range product,Regularly busy,Busiest day,Most orders,22,Regular customer,8.651049,Low spender
11,1870022,15,prior,17,2,16,8.0,196,6,1,...,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,22,Regular customer,8.328723,Low spender
12,1911383,15,prior,18,2,11,7.0,196,1,1,...,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,22,Regular customer,8.116216,Low spender
13,2715276,15,prior,21,1,9,7.0,196,1,1,...,9.0,both,Mid-range product,Regularly busy,Busiest day,Most orders,22,Regular customer,8.708642,Low spender
14,487368,15,prior,22,1,10,14.0,196,1,1,...,9.0,both,Mid-range product,Regularly busy,Busiest day,Most orders,22,Regular customer,8.014286,Low spender
15,2293453,19,prior,2,5,14,6.0,196,3,0,...,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,9,New customer,3.980556,Low spender
16,1973799,19,prior,5,6,12,8.0,196,15,1,...,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,9,New customer,8.228571,Low spender
17,532817,19,prior,7,4,17,6.0,196,1,1,...,9.0,both,Mid-range product,Least busy,slowest busy,Average orders,9,New customer,108.648299,High spender
18,1573906,21,prior,10,3,10,6.0,196,2,0,...,9.0,both,Mid-range product,Regularly busy,slowest busy,Most orders,33,Regular customer,7.702564,Low spender
19,1593000,31,prior,10,3,8,7.0,196,17,0,...,9.0,both,Mid-range product,Regularly busy,slowest busy,Average orders,20,Regular customer,8.372059,Low spender
20,2231262,31,prior,17,3,11,8.0,196,14,1,...,9.0,both,Mid-range product,Regularly busy,slowest busy,Most orders,20,Regular customer,5.409091,Low spender
21,2580647,43,prior,6,4,16,4.0,196,9,0,...,9.0,both,Mid-range product,Least busy,slowest busy,Most orders,11,Regular customer,7.012683,Low spender
22,2187180,43,prior,9,4,12,3.0,196,1,1,...,9.0,both,Mid-range product,Least busy,slowest busy,Most orders,11,Regular customer,7.427536,Low spender
23,2497897,52,prior,1,1,9,1.0,196,4,0,...,9.0,both,Mid-range product,Regularly busy,Busiest day,Most orders,27,Regular customer,8.222500,Low spender
24,1318871,52,prior,2,1,10,7.0,196,5,1,...,9.0,both,Mid-range product,Regularly busy,Busiest day,Most orders,27,Regular customer,6.742105,Low spender
25,1261384,52,prior,3,1,10,7.0,196,3,1,...,9.0,both,Mid-range product,Regularly busy,Busiest day,Most orders,27,Regular customer,8.257143,Low spender
26,580568,52,prior,5,2,10,8.0,196,6,1,...,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,27,Regular customer,6.783929,Low spender
27,2428073,52,prior,7,2,7,8.0,196,5,1,...,9.0,both,Mid-range product,Regularly busy,Regularly busy,Average orders,27,Regular customer,7.659269,Low spender
28,342306,52,prior,9,1,11,7.0,196,5,1,...,9.0,both,Mid-range product,Regularly busy,Busiest day,Most orders,27,Regular customer,8.355249,Low spender
29,1520353,52,prior,10,2,10,8.0,196,4,1,...,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,27,Regular customer,7.437333,Low spender
30,2542086,52,prior,11,2,9,7.0,196,3,1,...,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,27,Regular customer,9.436364,Low spender
31,944694,52,prior,12,1,16,6.0,196,7,1,...,9.0,both,Mid-range product,Regularly busy,Busiest day,Most orders,27,Regular customer,8.137793,Low spender
32,1268191,52,prior,15,2,11,8.0,196,3,1,...,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,27,Regular customer,7.571930,Low spender
33,1122089,52,prior,17,2,10,6.0,196,4,1,...,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,27,Regular customer,6.622642,Low spender
34,1498922,52,prior,18,2,10,14.0,196,6,1,...,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,27,Regular customer,7.046875,Low spender
35,180919,52,prior,19,3,8,8.0,196,4,1,...,9.0,both,Mid-range product,Regularly busy,slowest busy,Average orders,27,Regular customer,7.906522,Low spender
36,2695875,52,prior,21,5,10,30.0,196,1,1,...,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,27,Regular customer,7.285621,Low spender
37,3205960,67,prior,1,3,11,1.0,196,1,0,...,9.0,both,Mid-range product,Regularly busy,slowest busy,Most orders,24,Regular customer,8.036170,Low spender
38,970922,67,prior,2,1,15,5.0,196,2,1,...,9.0,both,Mid-range product,Regularly busy,Busiest day,Most orders,24,Regular customer,8.456477,Low spender
39,596585,67,prior,3,1,13,7.0,196,2,1,...,9.0,both,Mid-range product,Regularly busy,Busiest day,Most orders,24,Regular customer,7.141844,Low spender
40,2037087,67,prior,4,2,9,8.0,196,1,1,...,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,24,Regular customer,6.668269,Low spender
41,2474111,67,prior,5,3,14,8.0,196,2,1,...,9.0,both,Mid-range product,Regularly busy,slowest busy,Most orders,24,Regular customer,8.061538,Low spender
42,1568481,67,prior,6,3,12,7.0,196,2,1,...,9.0,both,Mid-range product,Regularly busy,slowest busy,Most orders,24,Regular customer,7.466165,Low spender
43,2048527,67,prior,8,2,11,7.0,196,1,1,...,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,24,Regular customer,7.444898,Low spender
44,2389031,67,prior,9,2,14,7.0,196,1,1,...,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,24,Regular customer,8.194595,Low spender
45,2378562,67,prior,10,1,10,6.0,196,1,1,...,9.0,both,Mid-range product,Regularly busy,Busiest day,Most orders,24,Regular customer,5.022222,Low spender
46,1515698,67,prior,11,1,11,7.0,196,1,1,...,9.0,both,Mid-range product,Regularly busy,Busiest day,Most orders,24,Regular customer,8.345223,Low spender
47,1928050,67,prior,12,2,12,8.0,196,1,1,...,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,24,Regular customer,8.676923,Low spender
48,1949274,67,prior,13,1,10,6.0,196,1,1,...,9.0,both,Mid-range product,Regularly busy,Busiest day,Most orders,24,Regular customer,8.066372,Low spender
49,551869,67,prior,14,1,9,7.0,196,1,1,...,9.0,both,Mid-range product,Regularly busy,Busiest day,Most orders,24,Regular customer,7.408511,Low spender

__Q.7 In order to send relevant notifications to users within the app (for instance, asking users if they want to buy the same item again), the Instacart team wants you to determine frequent versus non-frequent customers. Create an order frequency flag that marks the regularity of a user’s ordering behavior according to the median in the “days_since_prior_order” column. The criteria for the flag should be as follows:__

__If the median of “days_since_prior_order” is higher than 20, then the customer should be labeled a “Non-frequent customer.”__

__If the median is higher than 10 and lower than or equal to 20, then the customer should be labeled a “Regular customer.”__

__If the median is lower than or equal to 10, then the customer should be labeled a “Frequent customer.__

In [23]:
# Create median_freq
orders_products_merged['median_freq']=orders_products_merged.groupby('user_id').agg({'days_since_prior_order': ['mean']})

In [24]:
orders_products_merged.loc[orders_products_merged['median_freq'] >= 20, 'order_freq'] = 'Non-frequent customer.'

In [25]:
orders_products_merged.loc[(orders_products_merged['median_freq'] > 10)  & (orders_products_merged['median_freq'] <= 20), 'order_freq']= 'Regular customer.'

In [26]:
orders_products_merged.loc[orders_products_merged['median_freq'] <= 10, 'order_freq'] = 'Frequent customer'

In [27]:
orders_products_merged.head(50)

,order_id,user_id,eval_set,order_number,order_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,...,price_range,Busiest_day,Busiest_days,busiest_period_of_day,max_order,loyalty_flag,avg_price,spending_flag,median_freq,order_freq
0,2539329,1,prior,1,2,8,1.0,196,1,0,...,Mid-range product,Regularly busy,Regularly busy,Average orders,10,New customer,NaN,NaN,NaN,NaN
1,2398795,1,prior,2,3,7,15.0,196,1,1,...,Mid-range product,Regularly busy,slowest busy,Average orders,10,New customer,6.367797,Low spender,18.627119,Regular customer.
2,473747,1,prior,3,3,12,21.0,196,1,1,...,Mid-range product,Regularly busy,slowest busy,Most orders,10,New customer,7.515897,Low spender,14.969231,Regular customer.
3,2254736,1,prior,4,4,7,29.0,196,1,1,...,Mid-range product,Least busy,slowest busy,Average orders,10,New customer,8.197727,Low spender,10.295455,Regular customer.
4,431534,1,prior,5,4,15,28.0,196,1,1,...,Mid-range product,Least busy,slowest busy,Most orders,10,New customer,8.205556,Low spender,12.166667,Regular customer.
5,3367565,1,prior,6,2,7,19.0,196,1,1,...,Mid-range product,Regularly busy,Regularly busy,Average orders,10,New customer,9.189189,Low spender,10.486486,Regular customer.
6,550135,1,prior,7,1,9,20.0,196,1,1,...,Mid-range product,Regularly busy,Busiest day,Most orders,10,New customer,8.471429,Low spender,5.857143,Frequent customer
7,3108588,1,prior,8,1,14,14.0,196,2,1,...,Mid-range product,Regularly busy,Busiest day,Most orders,10,New customer,7.466990,Low spender,12.815534,Regular customer.
8,2295261,1,prior,9,1,16,0.0,196,4,1,...,Mid-range product,Regularly busy,Busiest day,Most orders,10,New customer,8.781633,Low spender,17.571429,Regular customer.
9,2550362,1,prior,10,4,8,30.0,196,1,1,...,Mid-range product,Least busy,slowest busy,Average orders,10,New customer,7.607895,Low spender,15.078947,Regular customer.
10,2968173,15,prior,15,1,9,7.0,196,2,0,...,Mid-range product,Regularly busy,Busiest day,Most orders,22,Regular customer,8.651049,Low spender,20.055944,Non-frequent customer.
11,1870022,15,prior,17,2,16,8.0,196,6,1,...,Mid-range product,Regularly busy,Regularly busy,Most orders,22,Regular customer,8.328723,Low spender,16.787234,Regular customer.
12,1911383,15,prior,18,2,11,7.0,196,1,1,...,Mid-range product,Regularly busy,Regularly busy,Most orders,22,Regular customer,8.116216,Low spender,25.148649,Non-frequent customer.
13,2715276,15,prior,21,1,9,7.0,196,1,1,...,Mid-range product,Regularly busy,Busiest day,Most orders,22,Regular customer,8.708642,Low spender,6.987654,Frequent customer
14,487368,15,prior,22,1,10,14.0,196,1,1,...,Mid-range product,Regularly busy,Busiest day,Most orders,22,Regular customer,8.014286,Low spender,24.009524,Non-frequent customer.
15,2293453,19,prior,2,5,14,6.0,196,3,0,...,Mid-range product,Regularly busy,Regularly busy,Most orders,9,New customer,3.980556,Low spender,10.472222,Regular customer.
16,1973799,19,prior,5,6,12,8.0,196,15,1,...,Mid-range product,Regularly busy,Regularly busy,Most orders,9,New customer,8.228571,Low spender,16.957143,Regular customer.
17,532817,19,prior,7,4,17,6.0,196,1,1,...,Mid-range product,Least busy,slowest busy,Average orders,9,New customer,108.648299,High spender,8.193878,Frequent customer
18,1573906,21,prior,10,3,10,6.0,196,2,0,...,Mid-range product,Regularly busy,slowest busy,Most orders,33,Regular customer,7.702564,Low spender,5.205128,Frequent customer
19,1593000,31,prior,10,3,8,7.0,196,17,0,...,Mid-range product,Regularly busy,slowest busy,Average orders,20,Regular customer,8.372059,Low spender,6.936275,Frequent customer
20,2231262,31,prior,17,3,11,8.0,196,14,1,...,Mid-range product,Regularly busy,slowest busy,Most orders,20,Regular customer,5.409091,Low spender,4.681818,Frequent customer
21,2580647,43,prior,6,4,16,4.0,196,9,0,...,Mid-range product,Least busy,slowest busy,Most orders,11,Regular customer,7.012683,Low spender,9.834146,Frequent customer
22,2187180,43,prior,9,4,12,3.0,196,1,1,...,Mid-range product,Least busy,slowest busy,Most orders,11,Regular customer,7.427536,Low spender,11.000000,Regular customer.
23,2497897,52,prior,1,1,9,1.0,196,4,0,...,Mid-range product,Regularly busy,Busiest day,Most orders,27,Regular customer,8.222500,Low spender,12.400000,Regular customer.
24,1318871,52,prior,2,1,10,7.0,196,5,1,...,Mid-range product,Regularly busy,Busiest day,Most orders,27,Regular customer,6.742105,Low spender,14.789474,Regular customer.
25,1261384,52,prior,3,1,10,7.0,196,3,1,...,Mid-range product,Regularly busy,Busiest day,Most orders,27,Regular customer,8.257143,Low spender,14.809524,Regular customer.
26,580568,52,prior,5,2,10,8.0,196,6,1,...,Mid-range product,Regularly busy,Regularly busy,Most orders,27,Regular customer,6.783929,Low spender,10.500000,Regular customer.
27,2428073,52,prior,7,2,7,8.0,196,5,1,...,Mid-range product,Regularly busy,Regularly busy,Average orders,27,Regular customer,7.659269,Low spender,5.124021,Frequent customer
28,342306,52,prior,9,1,11,7.0,196,5,1,...,Mid-range product,Regularly busy,Busiest day,Most orders,27,Regular customer,8.355249,Low spender,12.165746,Regular customer.
29,1520353,52,prior,10,2,10,8.0,196,4,1,...,Mid-range product,Regularly busy,Regularly busy,Most orders,27,Regular customer,7.437333,Low spender,11.217778,Regular customer.
30,2542086,52,prior,11,2,9,7.0,196,3,1,...,Mid-range product,Regularly busy,Regularly busy,Most orders,27,Regular customer,9.436364,Low spender,16.727273,Regular customer.
31,944694,52,prior,12,1,16,6.0,196,7,1,...,Mid-range product,Regularly busy,Busiest day,Most orders,27,Regular customer,8.137793,Low spender,5.852843,Frequent customer
32,1268191,52,prior,15,2,11,8.0,196,3,1,...,Mid-range product,Regularly busy,Regularly busy,Most orders,27,Regular customer,7.571930,Low spender,19.508772,Regular customer.
33,1122089,52,prior,17,2,10,6.0,196,4,1,...,Mid-range product,Regularly busy,Regularly busy,Most orders,27,Regular customer,6.622642,Low spender,16.679245,Regular customer.
34,1498922,52,prior,18,2,10,14.0,196,6,1,...,Mid-range product,Regularly busy,Regularly busy,Most orders,27,Regular customer,7.046875,Low spender,18.062500,Regular customer.
35,180919,52,prior,19,3,8,8.0,196,4,1,...,Mid-range product,Regularly busy,slowest busy,Average orders,27,Regular customer,7.906522,Low spender,18.956522,Regular customer.
36,2695875,52,prior,21,5,10,30.0,196,1,1,...,Mid-range product,Regularly busy,Regularly busy,Most orders,27,Regular customer,7.285621,Low spender,9.921569,Frequent customer
37,3205960,67,prior,1,3,11,1.0,196,1,0,...,Mid-range product,Regularly busy,slowest busy,Most orders,24,Regular customer,8.036170,Low spender,11.941489,Regular customer.
38,970922,67,prior,2,1,15,5.0,196,2,1,...,Mid-range product,Regularly busy,Busiest day,Most orders,24,Regular customer,8.456477,Low spender,21.367876,Non-frequent customer.
39,596585,67,prior,3,1,13,7.0,196,2,1,...,Mid-range product,Regularly busy,Busiest day,Most orders,24,Regular customer,7.141844,Low spender,11.957447,Regular customer.
40,2037087,67,prior,4,2,9,8.0,196,1,1,...,Mid-range product,Regularly busy,Regularly busy,Most orders,24,Regular customer,6.668269,Low spender,11.615385,Regular customer.
41,2474111,67,prior,5,3,14,8.0,196,2,1,...,Mid-range product,Regularly busy,slowest busy,Most orders,24,Regular customer,8.061538,Low spender,22.030769,Non-frequent customer.
42,1568481,67,prior,6,3,12,7.0,196,2,1,...,Mid-range product,Regularly busy,slowest busy,Most orders,24,Regular customer,7.466165,Low spender,12.496241,Regular customer.
43,2048527,67,prior,8,2,11,7.0,196,1,1,...,Mid-range product,Regularly busy,Regularly busy,Most orders,24,Regular customer,7.444898,Low spender,10.224490,Regular customer.
44,2389031,67,prior,9,2,14,7.0,196,1,1,...,Mid-range product,Regularly busy,Regularly busy,Most orders,24,Regular customer,8.194595,Low spender,22.945946,Non-frequent customer.
45,2378562,67,prior,10,1,10,6.0,196,1,1,...,Mid-range product,Regularly busy,Busiest day,Most orders,24,Regular customer,5.022222,Low spender,21.722222,Non-frequent customer.
46,1515698,67,prior,11,1,11,7.0,196,1,1,...,Mid-range product,Regularly busy,Busiest day,Most orders,24,Regular customer,8.345223,Low spender,16.904459,Regular customer.
47,1928050,67,prior,12,2,12,8.0,196,1,1,...,Mid-range product,Regularly busy,Regularly busy,Most orders,24,Regular customer,8.676923,Low spender,7.730769,Frequent customer
48,1949274,67,prior,13,1,10,6.0,196,1,1,...,Mid-range product,Regularly busy,Busiest day,Most orders,24,Regular customer,8.066372,Low spender,21.008850,Non-frequent customer.
49,551869,67,prior,14,1,9,7.0,196,1,1,...,Mid-range product,Regularly busy,Busiest day,Most orders,24,Regular customer,7.408511,Low spender,26.765957,Non-frequent customer.

__Import__

In [29]:
orders_products_merged.to_pickle(os.path.join(path,'02 Data','Prepared Data','orders_products_merged_aggregated.pkl'))